# Generated by Django 5.2.2 on 2025-06-05 00:16

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bicicleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Montaña", "Montaña"),
                            ("Ruta", "Ruta"),
                            ("Ciudad", "Ciudad"),
                            ("BMX", "BMX"),
                        ],
                        max_length=15,
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="bicicletas/"),
                ),
                (
                    "precio_por_dia",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("disponible_para_venta", models.BooleanField(default=False)),
                ("disponible_para_arriendo", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Arriendo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("Debito", "Débito"),
                            ("Credito", "Crédito"),
                            ("Transferencia", "Transferencia Bancaria"),
                        ],
                        max_length=20,
                    ),
                ),
                ("costo_arriendo", models.IntegerField(default=0)),
                ("deposito_garantia", models.IntegerField(default=100000)),
                ("costo_total", models.IntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completado", "Completado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bicicleta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.bicicleta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca_bicicleta", models.CharField(max_length=100)),
                (
                    "tipo_bicicleta",
                    models.CharField(
                        choices=[
                            ("MTB", "Montaña"),
                            ("RDB", "Ruta"),
                            ("CTY", "Ciudad"),
                            ("BMX", "BMX"),
                        ],
                        max_length=3,
                    ),
                ),
                ("descripcion_problema", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_reparacion",
                    models.CharField(
                        choices=[
                            ("Esperando producto.", "Esperando Producto"),
                            ("En reparacion", "En Reparacion"),
                            ("Listo para retirar", "Listo para el Retiro"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reparaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reparación",
                "verbose_name_plural": "Reparaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
