# Generated by Django 5.2.2 on 2025-06-05 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("tecnicos_vendedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reparacion",
            name="reserva_tecnico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reparaciones",
                to="tecnicos_vendedores.reservatecnico",
            ),
        ),
    ]
