# Generated by Django 5.2.2 on 2025-06-05 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Carro", "0001_initial"),
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcarro",
            name="bicicleta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.bicicleta"
            ),
        ),
        migrations.AddField(
            model_name="itemcarro",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_carro",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orden",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordenes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordenitem",
            name="bicicleta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.bicicleta"
            ),
        ),
        migrations.AddField(
            model_name="ordenitem",
            name="orden",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Carro.orden",
            ),
        ),
    ]
