# Generated by Django 5.2.3 on 2025-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Carro", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente de Pago", "Pendiente de Pago"),
                    ("Procesando Pedido", "Procesando"),
                    ("Pedido Confirmado", "Confirmado"),
                    ("Enviado", "Enviado"),
                    ("Entregado", "Entregado"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Procesando Pedido",
                max_length=20,
            ),
        ),
    ]
